### ISSUE TITLE
Rationale behind CursesReturnValue?

### ISSUE THREAD

**Issue by vain** [trehn/termdown#17]
The termdown source code says:

    curses.wrapper() does not provide the return value of the called
    function, so we use this hack to pass something through.

Agreed, it's not explicitly [documented](https://docs.python.org/3/library/curses.html#curses.wrapper), but `curses.wrapper()` does indeed provide a return value. I'm using that in several scripts, such as [choose](https://github.com/vain/bin-pub/blob/master/choose#L184). Works in Python 2 and 3.

IIUC, you could use a simple `return` in `stopwatch()`. Am I missing something?

**Comment by trehn** [comment]
I probably just got confused because `@graceful_ctrlc` ate the return value.
