### ISSUE TITLE
An ability to add message and title

### ISSUE THREAD

**Issue by pahakalle** [trehn/termdown#26]
An ability to add a text below and over the count down would be nice

**Comment by trehn** [comment]
`termdown -T hi 5`

**Comment by ScooterSam** [comment]
@trehn doesn't work dude^^

**Comment by trehn** [comment]
Works for me, can you be more specific?

**Comment by ScooterSam** [comment]
With the command you specified, and the window the size in this print screen, it appears like this:
http://shotsaver.idevelopthings.com/uploads/A6J1LHfCL20rdFrz.png
