### ISSUE TITLE
Exit status

### ISSUE THREAD

**Issue by asclepius** [trehn/termdown#27]
Would be nice to have different exit status codes for the different ways that the program terminated.

Something simple like a 0 for running to completion in countdown mode and 1 for Q being pressed.  Maybe others would disagree or want a different output.

My motivation is using it in a script as a pomdoro tracker to automatically updated a count at the end only if it ran to completion.  But certainly could be useful in other situations.

Really nice interface overall.  Thank you!

**Comment by BlitzKraft** [comment]
Instead of Q, you can hit Ctrl-C to have an exit status of 1.

**Comment by trehn** [comment]
I don't think there's any obvious way what's "right" here and people's scripts might already depend on the current behavior, so I'd rather not mess with it too much without really good cause. Using CTRL+C seems reasonable for your use case.
