### ISSUE TITLE
Question / Proposal

### ISSUE THREAD

**Issue by benyanke** [trehn/termdown#28]
Is there any implementation or plans for a config file for things like default font, default use of `alt-format`, display or non-display of seconds, etc....

**Comment by trehn** [comment]
No, you can just use a tiny wrapper script instead.

**Comment by benyanke** [comment]
Would you be open to a PR if I can implement an **optional** .termdownrc file cleanly?

**Comment by trehn** [comment]
Thanks, but I don't see the need. A config file makes sense for options you cannot pass as arguments. And termdown is small enough that it will always have everything available as an argument.
