### ISSUE TITLE
Feature requests: spoken countdown interval and options

### ISSUE THREAD

**Issue by sharethewisdom** [trehn/termdown#32]
I've used this tool for the first time today. Very useful.

One minor suggestion for change, though. When counting with a "real" stopwatch, people tend to only say every 10th second or so out loud, untill `--critical`, which is also counted. I'm not sure how you'd like your program to behave. Please consider adding an `--interval` option and an option `--onlyspeak` (`-o`) to go with `--voice`. `--onlyspeak` could, for example, have three values: `critical`, `interval` and/or `text`.

So the command
```
termdown -c 10 -i 10 -t stop 60 -v 'en-gb' -o 'critical,interval,text'
```
would trigger espeak to read "60..., 50..., 40..., 30..., 20..., 10,9,8,7,6,5,4,3,2,1,stop", and show the spoken numbers in red.

As an extra, a prefix would be nice: `-p 'T minus'` which would appear before the number until the count becomes `--critical`.

So the command
```
termdown -c 10 -i 10 -t launch 60 -v 'en-gb' -o 'critical,interval,text'
```
would effectively turn it into a simple rocket launch counter, because we need that, don't we? Espeak should read "tee minus 60 [...] tee minus 20..., 10,9,8,7,6,5,4,3,2,1,launch". :smile: :rocket:

**Comment by trehn** [comment]
I've implemented a simplified version of your suggestions in a7e21cc4694dc5e997e29ee6fddff23ed30bdbf9 and release 1.30.0 with these changes. Have fun.

🚀

**Comment by sharethewisdom** [comment]
oh wow thanks! A minor detail: I'd like espeak to say "launch" on time.

```
termdown -t launch -v 'en-gb' -p 't minus' -B -c 10 -q0 3 && espeak -p60 launch 2>/dev/null
```

`-q0` makes termdown exit with a lag of roughly 700ms.

**Comment by trehn** [comment]
How did you measure that lag?

```
$ time termdown 0

real	0m0.289s
user	0m0.234s
sys	0m0.051s
```

For me the lag is around 300ms, but it is incurred at the beginning, not the end. Most of it is spent in imports:

```
$ cat test.py
import curses
from datetime import datetime, timedelta
from functools import wraps
from math import ceil
try:
    from queue import Empty, Queue
except ImportError:
    from Queue import Empty, Queue
import re
import os
from os.path import abspath, dirname
from subprocess import Popen, STDOUT
try:
    from subprocess import DEVNULL
except ImportError:  # Python 2
    DEVNULL = open(os.devnull, 'wb')
from sys import exit, stderr, stdout
from threading import Event, Lock, Thread
from time import sleep
import unicodedata

import click
from dateutil import tz
from dateutil.parser import parse
from pyfiglet import CharNotPrinted, Figlet

$ time python3 test.py

real	0m0.281s
user	0m0.227s
sys	0m0.049s
```
