### ISSUE TITLE
Play custom bell/command at countdown while screen is flashing

### ISSUE THREAD

**Issue by bostrr** [trehn/termdown#42]
Hi would it be possible for you to add an option to specify a command or script to be run at countdown , so that a custom beep can be played for example?

**Comment by indeedwatson** [comment]
An option to play an audio file or even a link with youtube-dl would be awesome.

**Comment by Charon77** [comment]
Here's my attempt to this
https://github.com/Charon77/termdown/tree/script-execute

Example usage:
python3 termdown.py --exec-shell "espeak -v en-us"  10

the current second is put as the last positional argument, so the above would result to:

espeak -v en-us 10
espeak -v en-us 9
espeak -v en-us 8
.
.
.

**Comment by trehn** [comment]
`--exec-cmd` now released with 1.15.0
