### ISSUE TITLE
ImportError: No module named queque

### ISSUE THREAD

**Issue by Newexplorer** [trehn/termdown#62]
```
Traceback (most recent call last):
  File "/home/porter14/.local/bin/termdown", line 6, in <module>
    from termdown import main
  File "/home/porter14/.local/lib/python2.7/site-packages/termdown.py", line 8, in <module>
    from queue import Empty, Queue
ImportError: No module named queue

```
I added termdown temporarily to my $PATH by running PATH=$PATH:/home/porter14/.local/bin
Then I ran ' termdown 5m' in my terminal and I got the above mentioned error.
I googled the error and I saw a post:  https://stackoverflow.com/questions/33432426/importerror-no-module-named-queue

Problem is that I have no experience at all with Python and using the solutions mentioned in the webpage I got nowhere.

**Comment by trehn** [comment]
Python 2 is no longer supported, remove it from your system if you can and use Python 3 instead.
