### ISSUE TITLE
Number 1 not properly spaced from colon when using alt-format (-a)

### ISSUE THREAD

**Issue by SSBMTonberry** [trehn/termdown#66]
Hello, and thank you for this amazing tool!
This is more like a visually annoying issue, but I'm reporting it nonetheless.
When the `-a` option is used, the 1-character kinda merges with the colon, as it's not properly spaced.
Would this be an easy fix?
![image](https://user-images.githubusercontent.com/26206421/98465462-76c99e80-21c9-11eb-917c-0ac12d8a3abd.png)

EDIT: I'm using xfce4-terminal

**Comment by JokeNeverSoke** [comment]
@SSBMTonberry This would be a problem from pyfiglet, not termdown. And, I would rather see it as a feature of the default font that termdown uses (which is `univers`)

![Screen Shot 2020-12-16 at 12 41 07](https://user-images.githubusercontent.com/45055133/102305870-f9e5cd80-3f9b-11eb-926c-3c6b43f9e6c3.png)

You could try using some other font with the `-f [font]` options. Some available ones are [here](http://www.figlet.org/examples.html). I'm using the `banner` font here:

![Screen Shot 2020-12-16 at 12 44 14](https://user-images.githubusercontent.com/45055133/102306104-69f45380-3f9c-11eb-8a94-4f6f473056ea.png)
