### ISSUE TITLE
Use SI symbol for minutes (min) instead of "m"

### ISSUE THREAD

**Issue by prosoitos** [trehn/termdown#68]
I love the project! :slightly_smiling_face: 

My only small complaint is that the time does not respect the SI symbol for minutes, which is "min". I would much rather see that. "m" is the unit for meters and while, admittedly, there is little risk of confusion, I think that it'd be better.

Thanks for the project and for your time! :slightly_smiling_face:

**Comment by JokeNeverSoke** [comment]
While `m` could be ambiguous, in the context of stopwatch/countdown there should be no confusion. However, implementing custom units would be helpful, perhaps something similar to `--minute-unit [str]` or `--second-unit [str]`. This would be different to `--time-format` as the latter shows the full time.

**Comment by prosoitos** [comment]
Indeed, I was not worried about potential confusion in this context. It's more a question of respecting standards. An analogy might be grammar or spelling: in many cases a wrong grammar or spelling does not add any confusion, but it will make many cringe.

I use this app (which I really love!! thank you for it!! 🙂 ) during breaks in programming workshops and I would rather have something like "We will resume in 5min" show rather than "We will resume in 5m". The latter makes me feel that I made a grammar mistake for all to see.

**Comment by trehn** [comment]
while I appreciate standards of course, I don't think it's practical here because a) there is no risk of confusion and b) there is more value in having the text as short as possible
