### ISSUE TITLE
There are no bell at the end of countdown

### ISSUE THREAD

**Issue by toprak** [trehn/termdown#72]

**Comment by SamuelSwartzberg** [comment]
I have this problem as well, but in the meanwhile you can add `&& ` and then any command that makes a sound, which will execute when the timer is over. I use it with the mac builtin say like so `termdown 35m && say done`

**Comment by Serjeel-Ranjan-911** [comment]
this beep sound I use with countdown

```
# BEEP SOUNDS

play -q -n synth .1 sin 90 || echo -e "\a"
play -q -n synth .1 sin 180 || echo -e "\a"


play -q -n synth .1 sin 90 || echo -e "\a"
play -q -n synth .1 sin 180 || echo -e "\a"
```

**Comment by OlaoluwaM** [comment]
For me, the bell does not ring if my timer completes while my tmux session is locked

**Comment by Technetium1** [comment]
I would also like to voice support for this feature. Here's another beep sound
```play -q -n synth 1 sin 200-500 synth 0.8 sine fmod 20-500 || echo -e "\a"```

@OlaoluwaM maybe these will be of use https://stackoverflow.com/a/39180062 & https://jasonwryan.com/blog/2011/01/25/setting-urgent-hints-in-dwm/

**Comment by trehn** [comment]
`&&` is the way it's meant to be used
