### ISSUE TITLE
[FEATURE REQUEST] Add count till

### ISSUE THREAD

**Issue by SimonHryszko** [trehn/termdown#87]
Hey, 

I love your repo <3 
Hoveever would be great, I could say count till like `termdown --t 12:00:00` what would count until noon

**Comment by jetole** [comment]
Agreed. I did this via a bash wrapper script but I think it would be better if it was integrated into termdown.

**Comment by SimonHryszko** [comment]
Actually it's possible just I didn't know how to do it at the time, try following:
`termdown 15:00`
